import numpy as np

pred = np.genfromtxt('r2_pred.txt', delimiter=' ')
cross = np.genfromtxt('r2_cross_final.txt', delimiter=' ')

a = pred[:, 0:1] - np.maximum(pred[:, 1:2], pred[:, 2:3])
b = cross[:, 0:1] - np.maximum(cross[:, 1:2], cross[:, 2:3])

c = np.concatenate([a, b], 1)
print((a >= 0) * (b >= 0))

names = ['RPI','W875RX1','DPCERA3M086SBEA','CMRMTSPLx','RETAILx','INDPRO','IPFPNSS','IPFINAL','IPCONGD','IPDCONGD','IPNCONGD','IPBUSEQ','IPMAT','IPDMAT','IPNMAT','IPMANSICS','IPB51222S','IPFUELS','CUMFNS','HWI','HWIURATIO','CLF16OV','CE16OV','UNRATE','UEMPMEAN','UEMPLT5','UEMP5TO14','UEMP15OV','UEMP15T26','UEMP27OV','CLAIMSx','PAYEMS','USGOOD','CES1021000001','USCONS','MANEMP','DMANEMP','NDMANEMP','SRVPRD','USTPU','USWTRADE','USTRADE','USFIRE','USGOVT','CES0600000007','AWOTMAN','AWHMAN','HOUST','HOUSTNE','HOUSTMW','HOUSTS','HOUSTW','PERMIT','PERMITNE','PERMITMW','PERMITS','PERMITW','ACOGNO','AMDMNOx','ANDENOx','AMDMUOx','BUSINVx','ISRATIOx','M1SL','M2SL','M2REAL','BOGMBASE','TOTRESNS','NONBORRES','BUSLOANS','REALLN','NONREVSL','CONSPI','S&P 500','S&P: indust','S&P div yield','S&P PE ratio','FEDFUNDS','CP3Mx','TB3MS','TB6MS','GS1','GS5','GS10','AAA','BAA','COMPAPFFx','TB3SMFFM','TB6SMFFM','T1YFFM','T5YFFM','T10YFFM','AAAFFM','BAAFFM','TWEXAFEGSMTHx','EXSZUSx','EXJPUSx','EXUSUKx','EXCAUSx','WPSFD49207','WPSFD49502','WPSID61','WPSID62','OILPRICEx','PPICMM','CPIAUCSL','CPIAPPSL','CPITRNSL','CPIMEDSL','CUSR0000SAC','CUSR0000SAD','CUSR0000SAS','CPIULFSL','CUSR0000SA0L2','CUSR0000SA0L5','PCEPI','DDURRG3M086SBEA','DNDGRG3M086SBEA','DSERRG3M086SBEA','CES0600000008','CES2000000008','CES3000000008','UMCSENTx','DTCOLNVHFNM','DTCTHFNM','INVEST','VIXCLSx']
print(names[28])
print(names[75])
print(names[87])
